name: troubleshoot 1

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  security-golang:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities - Go
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      with:
        command:  monitor